version: "3.9"
services:
  redis:
    image: redislabs/redisearch:latest
    ports:
      - 6379:6379
  app:
    build: .
    command: ["python3", "test.py"]
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis